import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import Header from "./components/Header";
import Footer from "./components/Footer";
=======
import Header from "./_components/Header";
import Footer from "./_components/Footer";
>>>>>>> 4065198ea532d258c3492a3203f0a0d042b17f9e
import ProductPage from "./pages/product/[id]";
import CheckoutPage from "./pages/product/CheckOut";
import SignIn from "./SignIn";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <SignIn/>
        <Footer/>
      </body>
    </html>
  );
}
