import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Privacy Policy",
};

export default function PrivacyPolicy() {
  return (
    <div className="privacy-policy ">
      <h1 className="text-2xl md:text-4xl font-semibold text-center mb-5 bg-black text-white w-full py-10 md:py-20">
        Privacy Policy
      </h1>
      <div className="container mx-auto px-5 md:px-10 lg:px-20">
        <p className="text-lg font-semibold mb-5">
          Last updated October 26, 2024
        </p>
        <p className="text-base  mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="text-base  mb-4">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. .
        </p>

        <h2 className="text-2xl font-semibold  mt-8 mb-4">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-semibold  mt-6 mb-3">Interpretation</h3>
        <p className="text-base  mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or plural.
        </p>

        <h3 className="text-xl font-semibold  mt-6 mb-3">Definitions</h3>
        <p className="text-base  mb-4">
          For the purposes of this Privacy Policy:
        </p>

        <ul className="list-disc pl-6 space-y-2 text-base ">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by, or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest, or other securities entitled to vote for election
            of directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot; in
            this Agreement) refers to Silaaimachine Engineers, Bisra Road,
            Rourkela, Odisha - 769043.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device, or any other device by a website,
            containing the details of Your browsing history on that website
            among its many uses.
          </li>
          <li>
            <strong>Country</strong> refers to: Orissa, India.
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>Third-party Social Media Service</strong> refers to any
            website or any social network website through which a User can log
            in or create an account to use the Service.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website</strong> refers to Silaaimachine Engineers,
            accessible from{" "}
            <Link
              href={`${process.env.NEXT_PUBLIC_FRONTEND_BASE_URL}`}
              rel="external nofollow noopener"
              target="_blank"
              className="text-blue-500 hover:underline"
            >
              {process.env.NEXT_PUBLIC_FRONTEND_BASE_URL}
            </Link>
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold  mt-8 mb-4">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="text-xl font-semibold  mt-6 mb-3">
          Types of Data Collected
        </h3>
        <section className="space-y-8">
          {/* Personal Data Section */}
          <div>
            <h4 className="text-xl font-semibold mt-4 mb-4">Personal Data</h4>
            <p className="text-base ">
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base mt-4 mb-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>
          </div>

          {/* Usage Data Section */}
          <div>
            <h4 className="text-xl font-semibold mt-4 mb-4">Usage Data</h4>
            <p className="text-base ">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-base ">
              Usage Data may include information such as Your Device&aposs
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that You visit, the time and
              date of Your visit, the time spent on those pages, unique device
              identifiers, and other diagnostic data.
            </p>
            <p className="text-base ">
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile
              operating system, the type of mobile Internet browser You use,
              unique device identifiers, and other diagnostic data.
            </p>
            <p className="text-base ">
              We may also collect information that Your browser sends whenever
              You visit our Service or when You access the Service by or through
              a mobile device.
            </p>
          </div>
        </section>

        <section className="space-y-5">
          <div>
            <h4 className="text-xl font-semibold mt-5 mb-5">
              Information from Third-Party Social Media Services
            </h4>
            <p className="text-base ">
              The Company allows You to create an account and log in to use the
              Service through the following Third-party Social Media Services:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base ">
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>
            <p className="text-base ">
              If You decide to register through or otherwise grant us access to
              a Third-Party Social Media Service, We may collect Personal data
              that is already associated with Your Third-Party Social Media
              Service&aposs account, such as Your name, Your email address, Your
              activities, or Your contact list associated with that account.
            </p>
            <p className="text-base ">
              You may also have the option of sharing additional information
              with the Company through Your Third-Party Social Media
              Service&aposs account. If You choose to provide such information
              and Personal Data, during registration or otherwise, You are
              giving the Company permission to use, share, and store it in a
              manner consistent with this Privacy Policy.
            </p>
          </div>

          <div>
            <h4 className="text-xl font-semibold ">
              Tracking Technologies and Cookies
            </h4>
            <p className="text-base ">
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information. Tracking
              technologies used are beacons, tags, and scripts to collect and
              track information and to improve and analyze Our Service. The
              technologies We use may include:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base ">
              <li>
                <strong className="font-semibold ">
                  Cookies or Browser Cookies.
                </strong>{" "}
                A cookie is a small file placed on Your Device. You can instruct
                Your browser to refuse all Cookies or to indicate when a Cookie
                is being sent. However, if You do not accept Cookies, You may
                not be able to use some parts of our Service. Unless you have
                adjusted Your browser setting so that it will refuse Cookies,
                our Service may use Cookies.
              </li>
              <li>
                <strong className="font-semibold ">Web Beacons.</strong> Certain
                sections of our Service and our emails may contain small
                electronic files known as web beacons (also referred to as clear
                gifs, pixel tags, and single-pixel gifs) that permit the
                Company, for example, to count users who have visited those
                pages or opened an email and for other related website
                statistics (for example, recording the popularity of a certain
                section and verifying system and server integrity).
              </li>
            </ul>
            <p className="text-base ">
              Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
              Cookies. Persistent Cookies remain on Your personal computer or
              mobile device when You go offline, while Session Cookies are
              deleted as soon as You close Your web browser. You can learn more
              about cookies on{" "}
              <a
                href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies"
                target="_blank"
                className="text-blue-600 hover:underline"
              >
                TermsFeed website
              </a>{" "}
              article.
            </p>
            <p className="text-base ">
              We use both Session and Persistent Cookies for the purposes set
              out below:
            </p>

            <div className="space-y-4">
              <div>
                <p className="text-lg font-semibold  mt-4">
                  <strong>Necessary / Essential Cookies</strong>
                </p>
                <p className="text-base ">
                  <strong>Type:</strong> Session Cookies
                </p>
                <p className="text-base ">
                  <strong>Administered by:</strong> Us
                </p>
                <p className="text-base ">
                  <strong>Purpose:</strong> These Cookies are essential to
                  provide You with services available through the Website and to
                  enable You to use some of its features. They help to
                  authenticate users and prevent fraudulent use of user
                  accounts. Without these Cookies, the services that You have
                  asked for cannot be provided, and We only use these Cookies to
                  provide You with those services.
                </p>
              </div>

              <div>
                <p className="text-lg font-semibold ">
                  <strong>Cookies Policy / Notice Acceptance Cookies</strong>
                </p>
                <p className="text-base ">
                  <strong>Type:</strong> Persistent Cookies
                </p>
                <p className="text-base ">
                  <strong>Administered by:</strong> Us
                </p>
                <p className="text-base ">
                  <strong>Purpose:</strong> These Cookies identify if users have
                  accepted the use of cookies on the Website.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="space-y-6">
          <div>
            <p className="text-lg font-semibold mt-4 mb-4">
              <strong>Functionality Cookies</strong>
            </p>
            <p className="text-base ">
              <strong>Type:</strong> Persistent Cookies
            </p>
            <p className="text-base ">
              <strong>Administered by:</strong> Us
            </p>
            <p className="text-base ">
              <strong>Purpose:</strong> These Cookies allow us to remember
              choices You make when You use the Website, such as remembering
              your login details or language preference. The purpose of these
              Cookies is to provide You with a more personal experience and to
              avoid You having to re-enter your preferences every time You use
              the Website.
            </p>
          </div>

          <div>
            <p className="text-base ">
              For more information about the cookies we use and your choices
              regarding cookies, please visit our{" "}
              <a
                href="/cookies-policy"
                className="text-blue-600 hover:underline"
              >
                Cookies Policy
              </a>{" "}
              or the Cookies section of our{" "}
              <a
                href="/privacy-policy"
                className="text-blue-600 hover:underline"
              >
                Privacy Policy
              </a>
              .
            </p>
          </div>

          <div>
            <h3 className="text-xl font-semibold mb-4">
              Use of Your Personal Data
            </h3>
            <p className="text-base ">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="list-disc pl-5 space-y-3">
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">
                    To provide and maintain our Service
                  </strong>
                  , including to monitor the usage of our Service.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">
                    To manage Your Account:
                  </strong>{" "}
                  to manage Your registration as a user of the Service. The
                  Personal Data You provide can give You access to different
                  functionalities of the Service that are available to You as a
                  registered user.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">
                    For the performance of a contract:
                  </strong>{" "}
                  the development, compliance and undertaking of the purchase
                  contract for the products, items or services You have
                  purchased or of any other contract with Us through the
                  Service.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">To contact You:</strong> To
                  contact You by email, telephone calls, SMS, or other
                  equivalent forms of electronic communication, such as a mobile
                  application&aposs push notifications regarding updates or
                  informative communications related to the functionalities,
                  products or contracted services, including the security
                  updates, when necessary or reasonable for their
                  implementation.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">To provide You</strong>{" "}
                  with news, special offers and general information about other
                  goods, services and events which we offer that are similar to
                  those that you have already purchased or enquired about unless
                  You have opted not to receive such information.
                </p>
              </li>
            </ul>
          </div>
        </section>

        <section className="space-y-8">
          {/* Managing Requests Section */}
          <div>
            <p className="text-base  leading-relaxed">
              <strong className="font-semibold ">
                To manage Your requests:
              </strong>{" "}
              To attend and manage Your requests to Us.
            </p>
          </div>

          {/* Business Transfers Section */}
          <div>
            <p className="text-base  leading-relaxed">
              <strong className="font-semibold ">
                For business transfers:
              </strong>{" "}
              We may use Your information to evaluate or conduct a merger,
              divestiture, restructuring, reorganization, dissolution, or other
              sale or transfer of some or all of Our assets, whether as a going
              concern or as part of bankruptcy, liquidation, or similar
              proceeding, in which Personal Data held by Us about our Service
              users is among the assets transferred.
            </p>
          </div>

          {/* Other Purposes Section */}
          <div>
            <p className="text-base  leading-relaxed">
              <strong className="font-semibold ">For other purposes:</strong> We
              may use Your information for other purposes, such as data
              analysis, identifying usage trends, determining the effectiveness
              of our promotional campaigns and to evaluate and improve our
              Service, products, services, marketing and your experience.
            </p>
          </div>

          {/* Sharing Your Information Section */}
          <div>
            <p className="text-base  leading-relaxed mb-4">
              We may share Your personal information in the following
              situations:
            </p>
            <ul className="list-disc pl-5 space-y-3">
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">
                    With Service Providers:
                  </strong>{" "}
                  We may share Your personal information with Service Providers
                  to monitor and analyze the use of our Service, to contact You.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">
                    For business transfers:
                  </strong>{" "}
                  We may share or transfer Your personal information in
                  connection with, or during negotiations of, any merger, sale
                  of Company assets, financing, or acquisition of all or a
                  portion of Our business to another company.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">With Affiliates:</strong>{" "}
                  We may share Your information with Our affiliates, in which
                  case we will require those affiliates to honor this Privacy
                  Policy. Affiliates include Our parent company and any other
                  subsidiaries, joint venture partners or other companies that
                  We control or that are under common control with Us.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">
                    With business partners:
                  </strong>{" "}
                  We may share Your information with Our business partners to
                  offer You certain products, services or promotions.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">With other users:</strong>{" "}
                  When You share personal information or otherwise interact in
                  the public areas with other users, such information may be
                  viewed by all users and may be publicly distributed outside.
                  If You interact with other users or register through a
                  Third-Party Social Media Service, Your contacts on the
                  Third-Party Social Media Service may see Your name, profile,
                  pictures and description of Your activity. Similarly, other
                  users will be able to view descriptions of Your activity,
                  communicate with You and view Your profile.
                </p>
              </li>
              <li>
                <p className="text-base ">
                  <strong className="font-semibold ">With Your consent:</strong>{" "}
                  We may disclose Your personal information for any other
                  purpose with Your consent.
                </p>
              </li>
            </ul>
          </div>
        </section>

        <section className="space-y-8">
          {/* Retention of Your Personal Data Section */}
          <div>
            <h3 className="text-xl font-semibold  mb-4 mt-4">
              Retention of Your Personal Data
            </h3>
            <p className="text-base  leading-relaxed mb-4">
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-base  leading-relaxed">
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>
          </div>

          {/* Transfer of Your Personal Data Section */}
          <div>
            <h3 className="text-xl font-semibold  mb-4">
              Transfer of Your Personal Data
            </h3>
            <p className="text-base  leading-relaxed mb-4">
              Your information, including Personal Data, is processed at the
              Company&aposs operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of Your state, province, country or other
              governmental jurisdiction where the data protection laws may
              differ than those from Your jurisdiction.
            </p>
            <p className="text-base  leading-relaxed mb-4">
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer.
            </p>
            <p className="text-base  leading-relaxed">
              The Company will take all steps reasonably necessary to ensure
              that Your data is treated securely and in accordance with this
              Privacy Policy and no transfer of Your Personal Data will take
              place to an organization or a country unless there are adequate
              controls in place including the security of Your data and other
              personal information.
            </p>
          </div>
        </section>

        <section className="space-y-6">
          {/* Delete Your Personal Data Section */}
          <div>
            <h3 className="text-xl font-semibold  mb-4 mt-4">
              Delete Your Personal Data
            </h3>
            <p className="text-base  leading-relaxed mb-4">
              You have the right to delete or request that We assist in deleting
              the Personal Data that We have collected about You.
            </p>
            <p className="text-base  leading-relaxed mb-4">
              Our Service may give You the ability to delete certain information
              about You from within the Service.
            </p>
            <p className="text-base  leading-relaxed mb-4">
              You may update, amend, or delete Your information at any time by
              signing in to Your Account, if you have one, and visiting the
              account settings section that allows you to manage Your personal
              information. You may also contact Us to request access to,
              correct, or delete any personal information that You have provided
              to Us.
            </p>
            <p className="text-base  leading-relaxed">
              Please note, however, that We may need to retain certain
              information when we have a legal obligation or lawful basis to do
              so.
            </p>
          </div>

          {/* Disclosure of Your Personal Data Section */}
          <div>
            <h3 className="text-xl font-semibold  mb-4">
              Disclosure of Your Personal Data
            </h3>

            {/* Business Transactions Subsection */}
            <div>
              <h4 className="text-lg font-semibold  mb-2">
                Business Transactions
              </h4>
              <p className="text-base  leading-relaxed mb-4">
                If the Company is involved in a merger, acquisition, or asset
                sale, Your Personal Data may be transferred. We will provide
                notice before Your Personal Data is transferred and becomes
                subject to a different Privacy Policy.
              </p>
            </div>

            {/* Law Enforcement Subsection */}
            <div>
              <h4 className="text-lg font-semibold  mb-2">Law enforcement</h4>
              <p className="text-base  leading-relaxed mb-4">
                Under certain circumstances, the Company may be required to
                disclose Your Personal Data if required to do so by law or in
                response to valid requests by public authorities (e.g. a court
                or a government agency).
              </p>
            </div>

            {/* Other Legal Requirements Subsection */}
            <div>
              <h4 className="text-lg font-semibold  mb-2">
                Other legal requirements
              </h4>
              <p className="text-base  leading-relaxed mb-4">
                The Company may disclose Your Personal Data in the good faith
                belief that such action is necessary to:
              </p>
              <ul className="list-disc pl-5 space-y-2 text-base ">
                <li>Comply with a legal obligation</li>
                <li>
                  Protect and defend the rights or property of the Company
                </li>
                <li>
                  Prevent or investigate possible wrongdoing in connection with
                  the Service
                </li>
                <li>
                  Protect the personal safety of Users of the Service or the
                  public
                </li>
                <li>Protect against legal liability</li>
              </ul>
            </div>
          </div>

          {/* Security of Your Personal Data Section */}
          <div>
            <h3 className="text-xl font-semibold  mb-4">
              Security of Your Personal Data
            </h3>
            <p className="text-base  leading-relaxed">
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>
          </div>
        </section>

        <section className="space-y-8">
          {/* Children&aposs Privacy Section */}
          <div>
            <h2 className="text-2xl font-semibold  mb-4 mt-4">
              Children&aposs Privacy
            </h2>
            <p className="text-base  leading-relaxed mb-4">
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please
              contact Us. If We become aware that We have collected Personal
              Data from anyone under the age of 13 without verification of
              parental consent, We take steps to remove that information from
              Our servers.
            </p>
            <p className="text-base  leading-relaxed">
              If We need to rely on consent as a legal basis for processing Your
              information and Your country requires consent from a parent, We
              may require Your parent&aposs consent before We collect and use
              that information.
            </p>
          </div>

          {/* Links to Other Websites Section */}
          <div>
            <h2 className="text-2xl font-semibold  mb-4">
              Links to Other Websites
            </h2>
            <p className="text-base  leading-relaxed mb-4">
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third-party link, You will be
              directed to that third party&aposs site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>
            <p className="text-base  leading-relaxed">
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third-party sites or
              services.
            </p>
          </div>

          {/* Changes to this Privacy Policy Section */}
          <div>
            <h2 className="text-2xl font-semibold  mb-4">
              Changes to this Privacy Policy
            </h2>
            <p className="text-base  leading-relaxed mb-4">
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-base  leading-relaxed mb-4">
              We will let You know via email and/or a prominent notice on Our
              Service, prior to the change becoming effective and update the
              &quot;Last updated&quot; date at the top of this Privacy Policy.
            </p>
            <p className="text-base  leading-relaxed">
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </div>
        </section>

        <section className="space-y-6 mb-5 mt-4">
          {/* Section Title */}
          <h1 className="text-2xl font-semibold ">Contact Us</h1>

          {/* Body Content */}
          <p className="text-base  leading-relaxed">
            If you have any questions about this Privacy Policy, you can contact
            us:
          </p>

          {/* Contact Methods */}
          <div className="space-y-4">
            {/* Email */}
            <p className="text-base  leading-relaxed">
              By email:{" "}
              <a
                href="mailto:support@silaaimachines.com"
                className="text-blue-600 hover:text-blue-800"
              >
                support@silaaimachines.com
              </a>
            </p>

            {/* Website Contact Page */}
            <p className="text-base  leading-relaxed">
              By visiting this page on our website:{" "}
              <Link
                href={`${process.env.NEXT_PUBLIC_FRONTEND_BASE_URL}/contact-us`}
                className="text-blue-600 hover:text-blue-800"
                target="_blank"
                rel="noopener noreferrer"
              >
                {process.env.NEXT_PUBLIC_FRONTEND_BASE_URL}/contact-us
              </Link>
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
